version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "4321:4321"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - NODE_ENV=development
      - ROLLUP_SKIP_NODEJS_CHECKS=true
      - VITE_SKIP_NATIVE_EXTENSIONS=true
    command: npm run dev
    networks:
      - genascope-network
    depends_on:
      - backend

  backend:
    build:
      context: ../cancer-genix-backend
      dockerfile: Dockerfile
    command: bash -c "until nc -z db 3306; do echo 'Waiting for db...'; sleep 2; done; export PYTHONPATH=/app && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://genascope:genascope@db:3306/genascope
    networks:
      - genascope-network
    depends_on:
      - db
    volumes:
      - ../cancer-genix-backend:/app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=genascope
      - MYSQL_USER=genascope
      - MYSQL_PASSWORD=genascope
    volumes:
      - genascope-data:/var/lib/mysql
    networks:
      - genascope-network

networks:
  genascope-network:
    driver: bridge

volumes:
  genascope-data: